### ISSUE TITLE
类似项目

### ISSUE THREAD

**Issue by Riajyuu** [skyseraph/Soft-Tools#1]
受到另一个类型repo启发，我创建了https://github.com/EMLVIRUS/Amazing-Windows-Apps
不知repo主有没有兴趣[合作一下](mailto:EMLVIRUS@outlook.com)

**Comment by skyseraph** [comment]
欢迎~~ [Here~](mailto:skyseraph00@126.com)

**Comment by vnady** [comment]
Blog 'HardWare' can not open.

**Comment by skyseraph** [comment]
@vnady Already fixed， tkx~
